### PR TITLE
Addresses compilation errors with gfortran 4.8

### PR DESCRIPTION
**Pull request by brtnfld**
Errors were introduced in PR #4049.

### CODE REVIEW

**Review by lrknox — APPROVED** [review]

**Review by derobins — APPROVED** [review]

**Comment by derobins** [comment]
I feel like we need a `LOL` label
