### PR TITLE
Test opening unseekable file

### PR DESCRIPTION
**Pull request by mattjala**
Test for the issue described in #1498. 

This works in 1.12/1.14 and segfaults in 1.10, so this is a regression test.

### CODE REVIEW

**Comment by lrknox** [comment]
Rerunning the check where ttsafe failed - it's a know issue and often passes when rerun.  There's also this error in some other checks:

/home/runner/work/hdf5/hdf5/test/tfile.c: In function ‘test_unseekable_file’:
/home/runner/work/hdf5/hdf5/test/tfile.c:8146:1: error: label ‘error’ defined but not used [-Werror=unused-label]
 8146 | error:

Ypu'll probably need to fix that one.

**Review by lrknox — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]

File: test/tfile.c [hunk 1]
```diff
@@ -8419,10 +8462,11 @@ test_file(void)
...
     test_libver_bounds_low_high(driver_name);
-    test_libver_macros();  /* Test the macros for library version comparison */
-    test_libver_macros2(); /* Test the macros for library version comparison */
-    test_incr_filesize();  /* Test H5Fincrement_filesize() and H5Fget_eoa() */
-    test_min_dset_ohdr();  /* Test dataset object header minimization */
+    test_libver_macros();   /* Test the macros for library version comparison */
+    test_libver_macros2();  /* Test the macros for library version comparison */
+    test_incr_filesize();   /* Test H5Fincrement_filesize() and H5Fget_eoa() */
+    test_min_dset_ohdr();   /* Test dataset object header minimization */
+    test_unseekable_file(); /* Test attempting to open/create an unseekable file */
```
Comment (kalvdans) [inline test/tfile.c:8469]: No need to keep the comments aligned, better keep diff size down.

File: test/tfile.c [hunk 2]
```diff
@@ -8100,6 +8100,49 @@ test_min_dset_ohdr(void)
...
+**    Test that attempting to open an unseekable file fails gracefully
+**    without a segfault (see hdf5#1498)
+****************************************************************/
+static void
+test_unseekable_file(void)
+{
+    hid_t file_id = H5I_INVALID_HID; /* File ID */
+
+    /* Output message about test being performed */
+    MESSAGE(5, ("Testing creating/opening an unseekable file\n"));
```
Comment (kalvdans) [inline test/tfile.c:8115]: Maybe fflush(stdout) after this, to know which test that causes a Segmentation Fault.

**Review by kalvdans — APPROVED** [review]
Looks good besides two minor remarks.
