### ISSUE TITLE
1.12.2 and higher parallel build fails to compile with an MPI v2.2 implementation. Undefined reference to MPI_Type_create_hindexed_block 

### ISSUE THREAD

**Issue by corppeon** [HDFGroup/hdf5#3587]
Undefined reference to MPI_Type_create_hindexed_block link error with gcc and Platform MPI, HDF5_ENABLE_PARALLEL=True.

Platform MPI implements the MPI v2.2 API. There are references to the method MPI_Type_create_hindexed_block in H5Dchunk.c, H5D__chunk_collective_fill() method. These calls require the MPI v3.0 API or higher.

These H5Dchunk calls should be protected with a conditional define, similar to those used in H5Smpio.c (H5_CHECK_MPI_VERSION(3, 0)), and an alternative implementation, probably using MPI_Type_create_hindexed used for the older MPI API.

**Comment by wreckdump** [comment]
What distribution and version of MPI are you using? I've had similar problem with OpenMPI 4.1.5. Try using older version of OpenMPI or try using MPICH, instead.

**Comment by corppeon** [comment]
It's Platform MPI v9.01. We do use other MPIs as well. Other MPI distributions with a pre v3.0 API will see the same issue

**Comment by brtnfld** [comment]
I have submitted a PR to resolve the compilation problem. However, there are still failed tests with MPI-2. Unfortunately, there is insufficient drive to continue supporting MPI-2 beyond this point. This is mainly due to the small number of users who use MPI-2 and the significant resources required to fix/maintain it. We would need to add CI tests and workarounds for MPI bugs that have since been fixed. As a result, there are few situations in which it is essential to support it.

As a result, we have decided to remove support for MPI-2 in the upcoming 1.14 release officially.

Out of curiosity, what 1.12 feature do you want over what I assume is HDF5 1.8 on the system?

**Comment by corppeon** [comment]
we were previously using 1.12.1 which worked. Our motive for upgrading HDF5 to latest is to incorporate latest security fixes

**Comment by derobins** [comment]
FWIW, 1.12.3 will be the last release of HDF5 1.12, after which that maintenance branch will be retired. I'd highly recommend moving to 1.14.

**Comment by brtnfld** [comment]
We no longer support 1.12, and 1.14 does not support MPI 2.2, so I will close this issue.
