### ISSUE TITLE
2.0.0 fail to build with zlibng 2.3.3

### ISSUE THREAD

**Issue by braindevices** [HDFGroup/hdf5#6204]
***
 ⛔ **IMPORTANT**  ⛔
 Security issues should not be reported here! Instead, please
 report them privately as security vulnerabilities; see for more
 information https://github.com/HDFGroup/hdf5/security/policy
***

**Describe the bug**
build fail with zlib-ng 2.3.3
```
_deps/hdf5_zlib-src/gzread.c.in does not exist.
```
it has introduced changes that gzread.c.in does not exist.
current patch strategy is probably quite bad instead of really using patch file, we copy our own cmakelist into the zlibng package, which is very vulnerable to any cmake change made by zlib-ng

zlib-ng v2.3.3
HDF5 v2.0.0

**Comment by hyoklee** [comment]
Hi, @braindevices!

Thank you for testing zlilb-ng and your bug report.

Would you please test with develop branch?
I'm getting the following error with develop branch on Win-2025 / VS-2026 / vcpkg-installed zlib-ng:

`D:\a\actions\actions\src\H5Zdeflate.c(26,1): error C1083: Cannot open include file: 'zlib-ng.h': No such file or directory [D:\a\actions\actions\build\src\hdf5-static.vcxproj]`

I'd appreciate if you could give more information on your system (OS, compilers) and how you built it (e.g., cmake options).

**Comment by jhendersonHDF** [comment]
The build of external zlib-ng has been updated to use 2.3.3 without patching it with the changes in https://github.com/HDFGroup/hdf5/pull/6287.
