### ISSUE TITLE
1.14.4 doesn't compile for me with external zlib specified

### ISSUE THREAD

**Issue by corppeon** [HDFGroup/hdf5#4558]
cmake -S .. -G "Visual Studio 17 2022" -A "x64" -DBUILD_SHARED_LIBS="True" -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING="True" -DHDF5_ENABLE_Z_LIB_SUPPORT="True" -DHDF5_ENABLE_SZIP_SUPPORT="False" -DHDF5_ENABLE_SZIP_ENCODING="False" -DHDF5_PACKAGE_EXTLIBS="True" -DHDF5_BUILD_TOOLS="False" -DHDF5_BUILD_FORTRAN="False" -DHDF5_ENABLE_PARALLEL="False" -DHDF5_BUILD_CPP_LIB="False" -DHDF5_BUILD_JAVA="False" -DHDF5_BUILD_EXAMPLES="False" -DHDF5_BUILD_HL_LIB="True" -DHDF5_ALLOW_EXTERNAL_SUPPORT="NO" -DZLIB_LIBRARY="d:\work\zlib\lib\zlib.lib" -DZLIB_INCLUDE_DIR="d:\work\zlib\include"

Compile fails for 2 binaries;
D:\Work\hdf5-hdf5_1.14.4.3\hdf5-hdf5_1.14.4.3\test\direct_chunk.c(19,10): error C1083: Cannot open include file: 'zlib.
h': No such file or directory [D:\Work\hdf5-hdf5_1.14.4.3\hdf5-hdf5_1.14.4.3\build\test\direct_chunk.vcxproj]

D:\Work\hdf5-hdf5_1.14.4.3\hdf5-hdf5_1.14.4.3\test\chunk_info.c(43,10): error C1083: Cannot open include file: 'zlib.h'
: No such file or directory [D:\Work\hdf5-hdf5_1.14.4.3\hdf5-hdf5_1.14.4.3\build\test\chunk_info.vcxproj]

Works ok on Linux/GCC
Works ok with previous version 1.14.3
 
**Platform (please complete the following information)**
1.14.4
Windows 11
VS2022
CMake 3.29
ZLib 1.3.1

**Comment by byrnHDF** [comment]
Unfortunately, we moved the compression headers to a separate variable, because we do not expose the compression APIs, and because those two tests break that compression contract, they fail to compile. Evidently, linux is much more relaxed in preserving that contract then windows. And somehow our testing did not catch this issue.

You can easily solve this by adding "${HDF5_COMP_INCLUDE_DIRECTORIES};" to the target_include_directories for direct_chunk and chunk_info in the test/CMakeLists.txt file at lines 504 and 483.

**Comment by corppeon** [comment]
many thanks, works for me
