### ISSUE TITLE
[BUG] cannot build static build with 1.13.2

### ISSUE THREAD

**Issue by chacha21** [HDFGroup/hdf5#2102]
Windows 7 64 bits, latest Visual Studio 2019

I used to build HDF5 1.12.2 without any issue with CMake GUI.
I updated to 1.13.2 and now the static build fails with errors :

 ```
 ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(165,35): error C2065: 'H5T_NATIVE_SCHAR_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(206,35): error C2065: 'H5T_NATIVE_SHORT_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(247,33): error C2065: 'H5T_NATIVE_INT_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(288,34): error C2065: 'H5T_NATIVE_LONG_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(823,35): error C2065: 'H5T_NATIVE_LLONG_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(874,35): error C2065: 'H5T_NATIVE_FLOAT_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(905,36): error C2065: 'H5T_NATIVE_DOUBLE_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(936,37): error C2065: 'H5T_NATIVE_LDOUBLE_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(942,30): error C2065: 'H5T_POINTER_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(943,26): error C2065: 'H5T_HVL_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(944,30): error C2065: 'H5T_HOBJREF_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(945,34): error C2065: 'H5T_HDSETREGREF_COMP_ALIGN_g' : undeclared identifier
  ...\HDF5\1.13.2\build\vs2019\x64\src\H5Tinit.c(946,26): error C2065: 'H5T_REF_COMP_ALIGN_g' : undeclared identifier
```

Indeed, in 1.13.2, the H5T.c file does not contain those symbols any more (#1400 ?)

**Comment by byrnHDF** [comment]
Which CMake version and can you describe which options you changed from the default values.

**Comment by chacha21** [comment]
Problem solved.

I tried to repeat the whole process, and wiped out the entire CMake output build folder, instead of "Deleting cache" only. The problem does not occur any more, whatever the set of options I use.

I can't explain what happened first, the "H5Tinit.c" file now looks different.
I wonder if I could have initially messed up in with the build folder containing remains of a previous 1.12.2 build.

**Comment by byrnHDF** [comment]
> Problem solved.
> 
> I tried to repeat the whole process, and wiped out the entire CMake output build folder, instead of "Deleting cache" only. The problem does not occur any more, whatever the set of options I use.
> 
> I can't explain what happened first, the "H5Tinit.c" file now looks different. I wonder if I could have initially messed up in with the build folder containing remains of a previous 1.12.2 build.

It happens, no worries.
